@src/Fcg.Api/Fcg.Api.http

@host = https://localhost:7190

### Register
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "name": "Aluno FIAP",
  "email": "aluno@fiap.com.br",
  "password": "Senha@123"
}

### Login Admin
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@fcg.com",
  "password": "SUA_SENHA_ADMIN"
}
